
export const data = [
    
    "Wedding Venue",
    "Wedding Reception Venue",
    "Caterers",
    "Invitations",
    "Photographer",
    "Videographer",
    "DJ",
    "Wedding Band",
    "Flowers",
    "Wedding Night Accomodation",
    "Wedding Cake",
    "Transport - Her",
    "Transport - Him",
    "Transport - Family",
    "Wedding Dress",
    "Suits",
    "Hair & Make up",
    "Honeymoon",
    "Wedding Rings",
    "Decorations",
    "Hen Do",
    "Stag Do",
    "Officiant",
    "Vows",
    "Music",
    "Table Decorations",
    "Lighting",
    "Signage",
    "Invitations",
    "HashTags",
    "Insurance",
    "Engagement Party",
    "Thank You Notes",
    "Seating Plan",
    "Place Cards",
    "Favours",
    "Write Toasts/Speeches",
    "Games/Entertainment",
    "Wedding Planner/Coordinator",     
    "Marriage License/Legal Documents",   
    "Bridal Party Gifts",                   
    "Welcome Bags",
    "Guest Itinerary",       
    "Rehearsal Dinner",                     
    "Ceremony Programs",                    
    "Emergency Kit",
    "Day-Of Supplies",     
    "Guest Book or Alternative",            
    "Vendor Tips & Gratuity Envelopes",    
    "Registry",                            
    "Backup Plan for Weather",              
    "Post-Wedding Brunch",                  
    "Kids' Activities",
    "Childcare",         
    "Permits (Venue, Music, etc.)",        
    "Live Stream Setup",                    
    "Dress/Suit Alterations",               
    "Plan Day Timeline",         
 


];

export const roles = [

    ["Best Man",5,true],
    ["Usher",7,true], 
    ["Groomsmen",6,true],
    ["Maid of Honour",3,true], 
    ["Bridesmaid",4,true], 
    ["Mother of the Bride",11,true], 
    ["Father of the Bride",12,true],
    ["Mother of the Groom",13,true],
    ["Father of the Groom",14,true],
    ["Flower Girl",8,true], 
    ["Page Boy",9,true],
    ["Ring Bearer",10,true], 
    ["Bride",1,false], 
    ["Groom",2,false]

];


export const weddingTasks = [
  // ===== 12+ MONTHS =====
  {
    id: "wedding-planner",
    label: "Wedding Planner/Coordinator",
    group: "Core Planning",
    phase: "12+ Months",
    order: 1,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "insurance",
    label: "Insurance",
    group: "Core Planning",
    phase: "12+ Months",
    order: 2,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },

  // ===== 9–12 MONTHS =====
  {
    id: "wedding-venue",
    label: "Wedding Venue",
    group: "Venues",
    phase: "9–12 Months",
    order: 10,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "reception-venue",
    label: "Wedding Reception Venue",
    group: "Venues",
    phase: "9–12 Months",
    order: 11,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "officiant",
    label: "Officiant",
    group: "Ceremony",
    phase: "9–12 Months",
    order: 12,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "marriage-license",
    label: "Marriage License/Legal Documents",
    group: "Ceremony",
    phase: "9–12 Months",
    order: 13,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },

  // ===== 6–9 MONTHS =====
  {
    id: "photographer",
    label: "Photographer",
    group: "Media",
    phase: "6–9 Months",
    order: 20,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "videographer",
    label: "Videographer",
    group: "Media",
    phase: "6–9 Months",
    order: 21,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "livestream",
    label: "Live Stream Setup",
    group: "Media",
    phase: "6–9 Months",
    order: 22,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "caterers",
    label: "Caterers",
    group: "Food & Drink",
    phase: "6–9 Months",
    order: 23,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },

  // ===== 3–6 MONTHS =====
  {
    id: "dress",
    label: "Wedding Dress",
    group: "Attire",
    phase: "3–6 Months",
    order: 30,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "suits",
    label: "Suits",
    group: "Attire",
    phase: "3–6 Months",
    order: 31,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "alterations",
    label: "Dress/Suit Alterations",
    group: "Attire",
    phase: "3–6 Months",
    order: 32,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "hair-makeup",
    label: "Hair & Make up",
    group: "Beauty",
    phase: "3–6 Months",
    order: 33,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "rings",
    label: "Wedding Rings",
    group: "Attire",
    phase: "3–6 Months",
    order: 34,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },

  // ===== 1–3 MONTHS =====
  {
    id: "dj",
    label: "DJ",
    group: "Entertainment",
    phase: "1–3 Months",
    order: 40,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "band",
    label: "Wedding Band",
    group: "Entertainment",
    phase: "1–3 Months",
    order: 41,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "music",
    label: "Music",
    group: "Entertainment",
    phase: "1–3 Months",
    order: 42,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "flowers",
    label: "Flowers",
    group: "Decor",
    phase: "1–3 Months",
    order: 43,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "decorations",
    label: "Decorations",
    group: "Decor",
    phase: "1–3 Months",
    order: 44,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "table-decor",
    label: "Table Decorations",
    group: "Decor",
    phase: "1–3 Months",
    order: 45,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "lighting",
    label: "Lighting",
    group: "Decor",
    phase: "1–3 Months",
    order: 46,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "signage",
    label: "Signage",
    group: "Decor",
    phase: "1–3 Months",
    order: 47,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },

  // ===== FINAL MONTH =====
  {
    id: "invitations",
    label: "Invitations",
    group: "Stationery",
    phase: "Final Month",
    order: 50,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "hashtags",
    label: "HashTags",
    group: "Stationery",
    phase: "Final Month",
    order: 51,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "seating-plan",
    label: "Seating Plan",
    group: "Stationery",
    phase: "Final Month",
    order: 52,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "place-cards",
    label: "Place Cards",
    group: "Stationery",
    phase: "Final Month",
    order: 53,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "favours",
    label: "Favours",
    group: "Stationery",
    phase: "Final Month",
    order: 54,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "ceremony-programs",
    label: "Ceremony Programs",
    group: "Ceremony",
    phase: "Final Month",
    order: 55,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },

  // ===== WEDDING WEEK =====
  {
    id: "transport-her",
    label: "Transport - Her",
    group: "Transport",
    phase: "Wedding Week",
    order: 60,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "transport-him",
    label: "Transport - Him",
    group: "Transport",
    phase: "Wedding Week",
    order: 61,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "transport-family",
    label: "Transport - Family",
    group: "Transport",
    phase: "Wedding Week",
    order: 62,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "accommodation",
    label: "Wedding Night Accomodation",
    group: "Accommodation",
    phase: "Wedding Week",
    order: 63,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "emergency-kit",
    label: "Emergency Kit",
    group: "Logistics",
    phase: "Wedding Week",
    order: 64,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "day-of",
    label: "Day-Of Supplies",
    group: "Logistics",
    phase: "Wedding Week",
    order: 65,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "vendor-tips",
    label: "Vendor Tips & Gratuity Envelopes",
    group: "Logistics",
    phase: "Wedding Week",
    order: 66,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },

  // ===== WEDDING DAY =====
  {
    id: "vows",
    label: "Vows",
    group: "Ceremony",
    phase: "Wedding Day",
    order: 70,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "backup-weather",
    label: "Backup Plan for Weather",
    group: "Logistics",
    phase: "Wedding Day",
    order: 71,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },

  // ===== POST-WEDDING =====
  {
    id: "engagement-party",
    label: "Engagement Party",
    group: "Events",
    phase: "Post-Wedding",
    order: 80,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "hen-do",
    label: "Hen Do",
    group: "Events",
    phase: "Post-Wedding",
    order: 81,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "stag-do",
    label: "Stag Do",
    group: "Events",
    phase: "Post-Wedding",
    order: 82,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "rehearsal-dinner",
    label: "Rehearsal Dinner",
    group: "Events",
    phase: "Post-Wedding",
    order: 83,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "registry",
    label: "Registry",
    group: "Post-Wedding",
    phase: "Post-Wedding",
    order: 84,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "gifts",
    label: "Bridal Party Gifts",
    group: "Post-Wedding",
    phase: "Post-Wedding",
    order: 85,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "thank-you",
    label: "Thank You Notes",
    group: "Post-Wedding",
    phase: "Post-Wedding",
    order: 86,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
  {
    id: "honeymoon",
    label: "Honeymoon",
    group: "Post-Wedding",
    phase: "Post-Wedding",
    order: 87,
    status: "not_started",
    assignedTo: null,
    dueDate: null,
  },
];





export default {
    data, roles,
}