
export const data = [
    
    "Wedding Venue",
    "Wedding Reception Venue",
    "Caterers",
    "Invitations",
    "Photographer",
    "Videographer",
    "DJ",
    "Wedding Band",
    "Flowers",
    "Wedding Night Accomodation",
    "Wedding Cake",
    "Transport - Her",
    "Transport - Him",
    "Transport - Family",
    "Wedding Dress",
    "Suits",
    "Hair & Make up",
    "Honeymoon",
    "Wedding Rings",
    "Decorations",
    "Hen Do",
    "Stag Do",
    "Officiant",
    "Vows",
    "Music",
    "Table Decorations",
    "Lighting",
    "Signage",
    "Invitations",
    "HashTags",
    "Insurance",
    "Engagement Party",
    "Thank You Notes",
    "Seating Plan",
    "Place Cards",
    "Favours",
    "Write Toasts/Speeches",
    "Games/Entertainment",
    "Wedding Planner/Coordinator",     
    "Marriage License/Legal Documents",   
    "Bridal Party Gifts",                   
    "Welcome Bags",
    "Guest Itinerary",       
    "Rehearsal Dinner",                     
    "Ceremony Programs",                    
    "Emergency Kit",
    "Day-Of Supplies",     
    "Guest Book or Alternative",            
    "Vendor Tips & Gratuity Envelopes",    
    "Registry",                            
    "Backup Plan for Weather",              
    "Post-Wedding Brunch",                  
    "Kids' Activities",
    "Childcare",         
    "Permits (Venue, Music, etc.)",        
    "Live Stream Setup",                    
    "Dress/Suit Alterations",               
    "Plan Day Timeline",         
 


];

export const roles = [

    ["Best Man",5,true],
    ["Usher",7,true], 
    ["Groomsmen",6,true],
    ["Maid of Honour",3,true], 
    ["Bridesmaid",4,true], 
    ["Mother of the Bride",11,true], 
    ["Father of the Bride",12,true],
    ["Mother of the Groom",13,true],
    ["Father of the Groom",14,true],
    ["Flower Girl",8,true], 
    ["Page Boy",9,true],
    ["Ring Bearer",10,true], 
    ["Bride",1,false], 
    ["Groom",2,false]

];


export const weddingTasks = [
  // ===== 12–18 MONTHS =====
  {
    id: "wedding-planner",
    label: "Wedding Planner/Coordinator",
    group: "Core Planning",
    phase: "12–18 Months",
    order: 1,
    dueOffset: { monthsBefore: 18 },
    dependencies: [],
  },
  {
    id: "wedding-venue",
    label: "Wedding Venue",
    group: "Venues",
    phase: "12–18 Months",
    order: 2,
    dueOffset: { monthsBefore: 18 },
    dependencies: [],
  },
  {
    id: "reception-venue",
    label: "Wedding Reception Venue",
    group: "Venues",
    phase: "12–18 Months",
    order: 3,
    dueOffset: { monthsBefore: 18 },
    dependencies: ["wedding-venue"],
  },
  {
    id: "insurance",
    label: "Insurance",
    group: "Core Planning",
    phase: "12–18 Months",
    order: 4,
    dueOffset: { monthsBefore: 18 },
    dependencies: [],
  },
  {
    id: "officiant",
    label: "Officiant",
    group: "Ceremony",
    phase: "12–18 Months",
    order: 5,
    dueOffset: { monthsBefore: 15 },
    dependencies: ["wedding-venue"],
  },
  {
    id: "photographer",
    label: "Photographer",
    group: "Media",
    phase: "12–18 Months",
    order: 6,
    dueOffset: { monthsBefore: 15 },
    dependencies: ["wedding-venue"],
  },
  {
    id: "videographer",
    label: "Videographer",
    group: "Media",
    phase: "12–18 Months",
    order: 7,
    dueOffset: { monthsBefore: 15 },
    dependencies: ["wedding-venue"],
  },
  {
    id: "livestream",
    label: "Live Stream Setup",
    group: "Media",
    phase: "12–18 Months",
    order: 8,
    dueOffset: { monthsBefore: 12 },
    dependencies: ["wedding-venue"],
  },
  {
    id: "caterers",
    label: "Caterers",
    group: "Food & Drink",
    phase: "12–18 Months",
    order: 9,
    dueOffset: { monthsBefore: 12 },
    dependencies: ["reception-venue"],
  },

  // ===== 9–12 MONTHS =====
  {
    id: "marriage-license",
    label: "Marriage License/Legal Documents",
    group: "Ceremony",
    phase: "9–12 Months",
    order: 10,
    dueOffset: { monthsBefore: 9 },
    dependencies: ["officiant"],
  },
  {
    id: "dress",
    label: "Wedding Dress",
    group: "Attire",
    phase: "9–12 Months",
    order: 11,
    dueOffset: { monthsBefore: 12 },
    dependencies: [],
  },
  {
    id: "suits",
    label: "Suits",
    group: "Attire",
    phase: "9–12 Months",
    order: 12,
    dueOffset: { monthsBefore: 9 },
    dependencies: [],
  },
  {
    id: "engagement-party",
    label: "Engagement Party",
    group: "Events",
    phase: "9–12 Months",
    order: 13,
    dueOffset: { monthsBefore: 12 },
    dependencies: [],
  },

  // ===== 6–9 MONTHS =====
  {
    id: "alterations",
    label: "Dress/Suit Alterations",
    group: "Attire",
    phase: "6–9 Months",
    order: 14,
    dueOffset: { monthsBefore: 4 },
    dependencies: ["dress", "suits"],
  },
  {
    id: "hair-makeup",
    label: "Hair & Make up",
    group: "Beauty",
    phase: "6–9 Months",
    order: 15,
    dueOffset: { monthsBefore: 9 },
    dependencies: [],
  },
  {
    id: "rings",
    label: "Wedding Rings",
    group: "Attire",
    phase: "6–9 Months",
    order: 16,
    dueOffset: { monthsBefore: 6 },
    dependencies: [],
  },
  {
    id: "dj",
    label: "DJ",
    group: "Entertainment",
    phase: "6–9 Months",
    order: 17,
    dueOffset: { monthsBefore: 6 },
    dependencies: ["reception-venue"],
  },
  {
    id: "band",
    label: "Wedding Band",
    group: "Entertainment",
    phase: "6–9 Months",
    order: 18,
    dueOffset: { monthsBefore: 6 },
    dependencies: ["reception-venue"],
  },
  {
    id: "flowers",
    label: "Flowers",
    group: "Decor",
    phase: "6–9 Months",
    order: 19,
    dueOffset: { monthsBefore: 4 },
    dependencies: ["reception-venue"],
  },
  {
    id: "decorations",
    label: "Decorations",
    group: "Decor",
    phase: "6–9 Months",
    order: 20,
    dueOffset: { monthsBefore: 4 },
    dependencies: ["reception-venue"],
  },
  {
    id: "honeymoon",
    label: "Honeymoon",
    group: "Post-Wedding",
    phase: "6–9 Months",
    order: 21,
    dueOffset: { monthsBefore: 9 },
    dependencies: [],
  },
  {
    id: "hen-do",
    label: "Hen Do",
    group: "Events",
    phase: "6–9 Months",
    order: 22,
    dueOffset: { monthsBefore: 6 },
    dependencies: [],
  },
  {
    id: "stag-do",
    label: "Stag Do",
    group: "Events",
    phase: "6–9 Months",
    order: 23,
    dueOffset: { monthsBefore: 6 },
    dependencies: [],
  },
  {
    id: "rehearsal-dinner",
    label: "Rehearsal Dinner",
    group: "Events",
    phase: "6–9 Months",
    order: 24,
    dueOffset: { monthsBefore: 6 },
    dependencies: ["reception-venue"],
  },

  // ===== 3–6 MONTHS =====
  {
    id: "music",
    label: "Music",
    group: "Entertainment",
    phase: "3–6 Months",
    order: 25,
    dueOffset: { monthsBefore: 4 },
    dependencies: ["dj", "band"],
  },
  {
    id: "table-decor",
    label: "Table Decorations",
    group: "Decor",
    phase: "3–6 Months",
    order: 26,
    dueOffset: { monthsBefore: 3 },
    dependencies: ["decorations"],
  },
  {
    id: "lighting",
    label: "Lighting",
    group: "Decor",
    phase: "3–6 Months",
    order: 27,
    dueOffset: { monthsBefore: 4 },
    dependencies: ["reception-venue"],
  },
  {
    id: "signage",
    label: "Signage",
    group: "Decor",
    phase: "3–6 Months",
    order: 28,
    dueOffset: { monthsBefore: 3 },
    dependencies: ["decorations"],
  },
  {
    id: "registry",
    label: "Registry",
    group: "Post-Wedding",
    phase: "3–6 Months",
    order: 29,
    dueOffset: { monthsBefore: 4 },
    dependencies: [],
  },

  // ===== 1–3 MONTHS =====
  {
    id: "invitations",
    label: "Invitations",
    group: "Stationery",
    phase: "1–3 Months",
    order: 30,
    dueOffset: { monthsBefore: 3 },
    dependencies: [],
  },
  {
    id: "hashtags",
    label: "HashTags",
    group: "Stationery",
    phase: "1–3 Months",
    order: 31,
    dueOffset: { monthsBefore: 2 },
    dependencies: [],
  },
  {
    id: "seating-plan",
    label: "Seating Plan",
    group: "Stationery",
    phase: "1–3 Months",
    order: 32,
    dueOffset: { weeksBefore: 3 },
    dependencies: ["invitations"],
  },
  {
    id: "place-cards",
    label: "Place Cards",
    group: "Stationery",
    phase: "1–3 Months",
    order: 33,
    dueOffset: { weeksBefore: 2 },
    dependencies: ["seating-plan"],
  },
  {
    id: "favours",
    label: "Favours",
    group: "Stationery",
    phase: "1–3 Months",
    order: 34,
    dueOffset: { weeksBefore: 4 },
    dependencies: [],
  },
  {
    id: "ceremony-programs",
    label: "Ceremony Programs",
    group: "Ceremony",
    phase: "1–3 Months",
    order: 35,
    dueOffset: { weeksBefore: 4 },
    dependencies: ["officiant"],
  },
  {
    id: "gifts",
    label: "Bridal Party Gifts",
    group: "Post-Wedding",
    phase: "1–3 Months",
    order: 36,
    dueOffset: { weeksBefore: 4 },
    dependencies: [],
  },
  {
    id: "thank-you",
    label: "Thank You Notes",
    group: "Post-Wedding",
    phase: "1–3 Months",
    order: 37,
    dueOffset: { weeksBefore: 2 },
    dependencies: ["registry"],
  },

  // ===== FINAL MONTH =====
  {
    id: "transport-her",
    label: "Transport - Her",
    group: "Transport",
    phase: "Final Month",
    order: 38,
    dueOffset: { weeksBefore: 4 },
    dependencies: ["wedding-venue"],
  },
  {
    id: "transport-him",
    label: "Transport - Him",
    group: "Transport",
    phase: "Final Month",
    order: 39,
    dueOffset: { weeksBefore: 4 },
    dependencies: ["wedding-venue"],
  },
  {
    id: "transport-family",
    label: "Transport - Family",
    group: "Transport",
    phase: "Final Month",
    order: 40,
    dueOffset: { weeksBefore: 4 },
    dependencies: ["wedding-venue"],
  },
  {
    id: "accommodation",
    label: "Wedding Night Accommodation",
    group: "Accommodation",
    phase: "Final Month",
    order: 41,
    dueOffset: { weeksBefore: 4 },
    dependencies: [],
  },
  {
    id: "emergency-kit",
    label: "Emergency Kit",
    group: "Logistics",
    phase: "Final Month",
    order: 42,
    dueOffset: { weeksBefore: 2 },
    dependencies: [],
  },
  {
    id: "day-of",
    label: "Day-Of Supplies",
    group: "Logistics",
    phase: "Final Month",
    order: 43,
    dueOffset: { weeksBefore: 1 },
    dependencies: ["emergency-kit"],
  },
  {
    id: "vendor-tips",
    label: "Vendor Tips & Gratuity Envelopes",
    group: "Logistics",
    phase: "Final Month",
    order: 44,
    dueOffset: { weeksBefore: 1 },
    dependencies: [],
  },

  // ===== WEDDING WEEK =====
  {
    id: "vows",
    label: "Vows",
    group: "Ceremony",
    phase: "Wedding Week",
    order: 45,
    dueOffset: { weeksBefore: 1 },
    dependencies: [],
  },
  {
    id: "backup-weather",
    label: "Backup Plan for Weather",
    group: "Logistics",
    phase: "Wedding Week",
    order: 46,
    dueOffset: { weeksBefore: 1 },
    dependencies: ["reception-venue"],
  },
];


export const phaseOrder = {
  "12–18 Months": 1,
  "9–12 Months": 2,
  "6–9 Months": 3,
  "3–6 Months": 4,
  "1–3 Months": 5,
  "Final Month": 6,
  "Wedding Week": 7,
  "Wedding Day": 8,
  "Post-Wedding": 9,
};



export default {
    data, roles, phaseOrder,
}