const  currencyList = {

  "AED": { name: "United Arab Emirates Dirham", icon: "", symbol: "", active: false},
  "AFN": { name: "Afghan Afghani", icon: "", symbol: "", active: false},
  "ALL": { name: "Albanian Lek", icon: "", symbol: "", active: false},
  "AMD": { name: "Armenian Dram", icon: "", symbol: "", active: false},
  "ANG": { name: "Netherlands Antillean Guilder", icon: "", symbol: "", active: false},
  "AOA": { name: "Angolan Kwanza", icon: "", symbol: "", active: false},
  "ARS": { name: "Argentine Peso", icon: "", symbol: "", active: false},
  "AUD": { name: "Australian Dollar", icon: "", symbol: "", active: false},
  "AWG": { name: "Aruban Florin", icon: "", symbol: "", active: false},
  "AZN": { name: "Azerbaijani Manat", icon: "", symbol: "", active: false},
  "BAM": { name: "Bosnia-Herzegovina Convertible Mark", icon: "", symbol: "", active: false},
  "BBD": { name: "Barbadian Dollar", icon: "", symbol: "", active: false},
  "BDT": { name: "Bangladeshi Taka", icon: "", symbol: "", active: false},
  "BGN": { name: "Bulgarian Lev", icon: "", symbol: "", active: false},
  "BHD": { name: "Bahraini Dinar", icon: "", symbol: "", active: false},
  "BIF": { name: "Burundian Franc", icon: "", symbol: "", active: false},
  "BMD": { name: "Bermudan Dollar", icon: "", symbol: "", active: false},
  "BND": { name: "Brunei Dollar", icon: "", symbol: "", active: false},
  "BOB": { name: "Bolivian Boliviano", icon: "", symbol: "", active: false},
  "BRL": { name: "Brazilian Real", icon: "", symbol: "", active: false},
  "BSD": { name: "Bahamian Dollar", icon: "", symbol: "", active: false},
  "BTC": { name: "Bitcoin", icon: "", symbol: "", active: false},
  "BTN": { name: "Bhutanese Ngultrum", icon: "", symbol: "", active: false},
  "BWP": { name: "Botswanan Pula", icon: "", symbol: "", active: false},
  "BYN": { name: "Belarusian Ruble", icon: "", symbol: "", active: false},
  "BZD": { name: "Belize Dollar", icon: "", symbol: "", active: false},
  "CAD": { name: "Canadian Dollar", icon: "", symbol: "", active: false},
  "CDF": { name: "Congolese Franc", icon: "", symbol: "", active: false},
  "CHF": { name: "Swiss Franc", icon: "ch", symbol: "₣", active: true},
  "CLF": { name: "Chilean Unit of Account (UF)", icon: "", symbol: "", active: false},
  "CLP": { name: "Chilean Peso", icon: "", symbol: "", active: false},
  "CNH": { name: "Chinese Yuan (Offshore)", icon: "", symbol: "", active: false},
  "CNY": { name: "Chinese Yuan", icon: "", symbol: "", active: false},
  "COP": { name: "Colombian Peso", icon: "", symbol: "", active: false},
  "CRC": { name: "Costa Rican Colón", icon: "", symbol: "", active: false},
  "CUC": { name: "Cuban Convertible Peso", icon: "", symbol: "", active: false},
  "CUP": { name: "Cuban Peso", icon: "", symbol: "", active: false},
  "CVE": { name: "Cape Verdean Escudo", icon: "", symbol: "", active: false},
  "CZK": { name: "Czech Republic Koruna", icon: "", symbol: "", active: false},
  "DJF": { name: "Djiboutian Franc", icon: "", symbol: "", active: false},
  "DKK": { name: "Danish Krone", icon: "", symbol: "", active: false},
  "DOP": { name: "Dominican Peso", icon: "", symbol: "", active: false},
  "DZD": { name: "Algerian Dinar", icon: "", symbol: "", active: false},
  "EGP": { name: "Egyptian Pound", icon: "", symbol: "", active: false},
  "ERN": { name: "Eritrean Nakfa", icon: "", symbol: "", active: false},
  "ETB": { name: "Ethiopian Birr", icon: "", symbol: "", active: false},
  "EUR": { name: "Euro", icon: "eu", symbol: "€", active: true},
  "FJD": { name: "Fijian Dollar", icon: "", symbol: "", active: false},
  "FKP": { name: "Falkland Islands Pound", icon: "", symbol: "", active: false},
  "GBP": { name: "British Pound Sterling", icon: "gb", symbol: "£", active: true},
  "GEL": { name: "Georgian Lari", icon: "", symbol: "", active: false},
  "GGP": { name: "Guernsey Pound", icon: "", symbol: "", active: false},
  "GHS": { name: "Ghanaian Cedi", icon: "", symbol: "", active: false},
  "GIP": { name: "Gibraltar Pound", icon: "", symbol: "", active: false},
  "GMD": { name: "Gambian Dalasi", icon: "", symbol: "", active: false},
  "GNF": { name: "Guinean Franc", icon: "", symbol: "", active: false},
  "GTQ": { name: "Guatemalan Quetzal", icon: "", symbol: "", active: false},
  "GYD": { name: "Guyanaese Dollar", icon: "", symbol: "", active: false},
  "HKD": { name: "Hong Kong Dollar", icon: "", symbol: "", active: false},
  "HNL": { name: "Honduran Lempira", icon: "", symbol: "", active: false},
  "HRK": { name: "Croatian Kuna", icon: "", symbol: "", active: false},
  "HTG": { name: "Haitian Gourde", icon: "", symbol: "", active: false},
  "HUF": { name: "Hungarian Forint", icon: "", symbol: "", active: false},
  "IDR": { name: "Indonesian Rupiah", icon: "", symbol: "", active: false},
  "ILS": { name: "Israeli New Sheqel", icon: "", symbol: "", active: false},
  "IMP": { name: "Manx pound", icon: "", symbol: "", active: false},
  "INR": { name: "Indian Rupee", icon: "", symbol: "", active: false},
  "IQD": { name: "Iraqi Dinar", icon: "", symbol: "", active: false},
  "IRR": { name: "Iranian Rial", icon: "", symbol: "", active: false},
  "ISK": { name: "Icelandic Króna", icon: "", symbol: "", active: false},
  "JEP": { name: "Jersey Pound", icon: "", symbol: "", active: false},
  "JMD": { name: "Jamaican Dollar", icon: "", symbol: "", active: false},
  "JOD": { name: "Jordanian Dinar", icon: "", symbol: "", active: false},
  "JPY": { name: "Japanese Yen", icon: "jp", symbol: "¥", active: true},
  "KES": { name: "Kenyan Shilling", icon: "", symbol: "", active: false},
  "KGS": { name: "Kyrgystani Som", icon: "", symbol: "", active: false},
  "KHR": { name: "Cambodian Riel", icon: "", symbol: "", active: false},
  "KMF": { name: "Comorian Franc", icon: "", symbol: "", active: false},
  "KPW": { name: "North Korean Won", icon: "", symbol: "", active: false},
  "KRW": { name: "South Korean Won", icon: "", symbol: "", active: false},
  "KWD": { name: "Kuwaiti Dinar", icon: "", symbol: "", active: false},
  "KYD": { name: "Cayman Islands Dollar", icon: "", symbol: "", active: false},
  "KZT": { name: "Kazakhstani Tenge", icon: "", symbol: "", active: false},
  "LAK": { name: "Laotian Kip", icon: "", symbol: "", active: false},
  "LBP": { name: "Lebanese Pound", icon: "", symbol: "", active: false},
  "LKR": { name: "Sri Lankan Rupee", icon: "", symbol: "", active: false},
  "LRD": { name: "Liberian Dollar", icon: "", symbol: "", active: false},
  "LSL": { name: "Lesotho Loti", icon: "", symbol: "", active: false},
  "LYD": { name: "Libyan Dinar", icon: "", symbol: "", active: false},
  "MAD": { name: "Moroccan Dirham", icon: "", symbol: "", active: false},
  "MDL": { name: "Moldovan Leu", icon: "", symbol: "", active: false},
  "MGA": { name: "Malagasy Ariary", icon: "", symbol: "", active: false},
  "MKD": { name: "Macedonian Denar", icon: "", symbol: "", active: false},
  "MMK": { name: "Myanma Kyat", icon: "", symbol: "", active: false},
  "MNT": { name: "Mongolian Tugrik", icon: "", symbol: "", active: false},
  "MOP": { name: "Macanese Pataca", icon: "", symbol: "", active: false},
  "MRU": { name: "Mauritanian Ouguiya", icon: "", symbol: "", active: false},
  "MUR": { name: "Mauritian Rupee", icon: "", symbol: "", active: false},
  "MVR": { name: "Maldivian Rufiyaa", icon: "", symbol: "", active: false},
  "MWK": { name: "Malawian Kwacha", icon: "", symbol: "", active: false},
  "MXN": { name: "Mexican Peso", icon: "", symbol: "", active: false},
  "MYR": { name: "Malaysian Ringgit", icon: "", symbol: "", active: false},
  "MZN": { name: "Mozambican Metical", icon: "", symbol: "", active: false},
  "NAD": { name: "Namibian Dollar", icon: "", symbol: "", active: false},
  "NGN": { name: "Nigerian Naira", icon: "", symbol: "", active: false},
  "NIO": { name: "Nicaraguan Córdoba", icon: "", symbol: "", active: false},
  "NOK": { name: "Norwegian Krone", icon: "", symbol: "", active: false},
  "NPR": { name: "Nepalese Rupee", icon: "", symbol: "", active: false},
  "NZD": { name: "New Zealand Dollar", icon: "", symbol: "", active: false},
  "OMR": { name: "Omani Rial", icon: "", symbol: "", active: false},
  "PAB": { name: "Panamanian Balboa", icon: "", symbol: "", active: false},
  "PEN": { name: "Peruvian Nuevo Sol", icon: "", symbol: "", active: false},
  "PGK": { name: "Papua New Guinean Kina", icon: "", symbol: "", active: false},
  "PHP": { name: "Philippine Peso", icon: "", symbol: "", active: false},
  "PKR": { name: "Pakistani Rupee", icon: "", symbol: "", active: false},
  "PLN": { name: "Polish Zloty", icon: "", symbol: "", active: false},
  "PYG": { name: "Paraguayan Guarani", icon: "", symbol: "", active: false},
  "QAR": { name: "Qatari Rial", icon: "", symbol: "", active: false},
  "RON": { name: "Romanian Leu", icon: "", symbol: "", active: false},
  "RSD": { name: "Serbian Dinar", icon: "", symbol: "", active: false},
  "RUB": { name: "Russian Ruble", icon: "", symbol: "", active: false},
  "RWF": { name: "Rwandan Franc", icon: "", symbol: "", active: false},
  "SAR": { name: "Saudi Riyal", icon: "", symbol: "", active: false},
  "SBD": { name: "Solomon Islands Dollar", icon: "", symbol: "", active: false},
  "SCR": { name: "Seychellois Rupee", icon: "", symbol: "", active: false},
  "SDG": { name: "Sudanese Pound", icon: "", symbol: "", active: false},
  "SEK": { name: "Swedish Krona", icon: "", symbol: "", active: false},
  "SGD": { name: "Singapore Dollar", icon: "", symbol: "", active: false},
  "SHP": { name: "Saint Helena Pound", icon: "", symbol: "", active: false},
  "SLE": { name: "Sierra Leonean Leone", icon: "", symbol: "", active: false},
  "SLL": { name: "Sierra Leonean Leone (Old)", icon: "", symbol: "", active: false},
  "SOS": { name: "Somali Shilling", icon: "", symbol: "", active: false},
  "SRD": { name: "Surinamese Dollar", icon: "", symbol: "", active: false},
  "SSP": { name: "South Sudanese Pound", icon: "", symbol: "", active: false},
  "STD": { name: "São Tomé and Príncipe Dobra (pre-2018)", icon: "", symbol: "", active: false},
  "STN": { name: "São Tomé and Príncipe Dobra", icon: "", symbol: "", active: false},
  "SVC": { name: "Salvadoran Colón", icon: "", symbol: "", active: false},
  "SYP": { name: "Syrian Pound", icon: "", symbol: "", active: false},
  "SZL": { name: "Swazi Lilangeni", icon: "", symbol: "", active: false},
  "THB": { name: "Thai Baht", icon: "", symbol: "", active: false},
  "TJS": { name: "Tajikistani Somoni", icon: "", symbol: "", active: false},
  "TMT": { name: "Turkmenistani Manat", icon: "", symbol: "", active: false},
  "TND": { name: "Tunisian Dinar", icon: "", symbol: "", active: false},
  "TOP": { name: "Tongan Pa'anga", icon: "", symbol: "", active: false},
  "TRY": { name: "Turkish Lira", icon: "", symbol: "", active: false},
  "TTD": { name: "Trinidad and Tobago Dollar", icon: "", symbol: "", active: false},
  "TWD": { name: "New Taiwan Dollar", icon: "", symbol: "", active: false},
  "TZS": { name: "Tanzanian Shilling", icon: "", symbol: "", active: false},
  "UAH": { name: "Ukrainian Hryvnia", icon: "", symbol: "", active: false},
  "UGX": { name: "Ugandan Shilling", icon: "", symbol: "", active: false},
  "USD": { name: "United States Dollar", icon: "US", symbol: "$", active: true},
  "UYU": { name: "Uruguayan Peso", icon: "", symbol: "", active: false},
  "UZS": { name: "Uzbekistan Som", icon: "", symbol: "", active: false},
  "VES": { name: "Venezuelan Bolívar Soberano", icon: "", symbol: "", active: false},
  "VND": { name: "Vietnamese Dong", icon: "", symbol: "", active: false},
  "VUV": { name: "Vanuatu Vatu", icon: "", symbol: "", active: false},
  "WST": { name: "Samoan Tala", icon: "", symbol: "", active: false},
  "XAF": { name: "CFA Franc BEAC", icon: "", symbol: "", active: false},
  "XAG": { name: "Silver Ounce", icon: "", symbol: "", active: false},
  "XAU": { name: "Gold Ounce", icon: "", symbol: "", active: false},
  "XCD": { name: "East Caribbean Dollar", icon: "", symbol: "", active: false},
  "XCG": { name: "Caribbean Guilder", icon: "", symbol: "", active: false},
  "XOF": { name: "CFA Franc BCEAO", icon: "", symbol: "", active: false},
  "XPD": { name: "Palladium Ounce", icon: "", symbol: "", active: false},
  "XPF": { name: "CFP Franc", icon: "", symbol: "", active: false},
  "XPT": { name: "Platinum Ounce", icon: "", symbol: "", active: false},
  "YER": { name: "Yemeni Rial", icon: "", symbol: "", active: false},
  "ZAR": { name: "South African Rand", icon: "SA", symbol: "", active: false},
  "ZMW": { name: "Zambian Kwacha", icon: "", symbol: "", active: false},
  "ZWG": { name: "Zimbabwean ZiG", icon: "", symbol: "", active: false},
  "ZWL": { name: "Zimbabwean Dollar", icon: "", symbol: "", active: false}


}


export default currencyList;